name: 'Extra Highlight Feature'
description: "Generates configuration and sample content for the Highlight Feature block."
type: 'Site'
install:
  - block
  - block_content
  - paragraphs
  - file
  - image
  - options
  - text
config: 
  strict: false
